Vagrant.configure("2") do |config|
  config.vm.define "sandbox" do |sandbox|
    sandbox.vm.box = "ubuntu/bionic64"
    sandbox.vm.hostname = "sandbox.internal.lan"
    sandbox.vm.network :private_network, ip: "192.168.100.99"
    sandbox.vm.synced_folder "src/", "/opt/src", create: true

    sandbox.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "sandbox"]
    end
    
    sandbox.vm.provision "ansible_local" do |ansible|
       ansible.install_mode = "default"
       ansible.version = "latest"
       ansible.playbook = "/opt/src/playbook.yml"
       ansible.galaxy_role_file = "/opt/src/requirements.yml"
       ansible.limit = "all,localhost"

       
    end
  end

end
