Vagrant.configure("2") do |config|
  config.vm.define "sandbox" do |sandbox|
    sandbox.vm.box = "geerlingguy/centos7"
    sandbox.vm.hostname = "sandbox.internal.lan"
    sandbox.vm.network :private_network, ip: "192.169.100.73"
    sandbox.vm.synced_folder "src/", "/opt/src", create: true

    sandbox.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "sandbox"]
    end
  end

end
