---
- hosts: localhost 
  connection: local
  become: yes
  roles:
    - role: andrewrothstein.go
  tasks:
    - name: Installing git
      package:
         name: git
         state: present
    - name: Compiling gb 
      command: /usr/local/go/bin/go get github.com/constabulary/gb/...
    - name: Copying gb binaries to /usr/local/bin
      copy: remote_src=yes src=/root/go/bin/gb dest=/usr/local/bin mode=o+rx
    - copy: remote_src=yes src=/root/go/bin/gb-vendor dest=/usr/local/bin mode=o+rx
    - name: Cleaning up binaries after copy
      file: path=/root/go state=absent

      
