Vagrant.configure("2") do |config|
  config.vm.define "ansiblebox" do |ansiblebox|
    ansiblebox.vm.box = "geerlingguy/centos7"
    ansiblebox.vm.hostname = "ansiblebox.internal.lan"
    ansiblebox.vm.network :private_network, ip: "192.169.100.73"
    ansiblebox.vm.synced_folder "src/", "/opt/src", create: true

    ansiblebox.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "ansiblebox"]
    end
    
    ansiblebox.vm.provision "ansible_local" do |ansible|
       ansible.install_mode = "pip"
       ansible.version = "latest"
       ansible.playbook = "/opt/src/playbook.yml"
       ansible.limit = "all,localhost"
       
    end
  end

end
