Vagrant.configure("2") do |config|
   (1..3).each do |i|
      config.vm.define "node-#{i}" do |node|
         node.vm.box = "geerlingguy/centos7"
         node.vm.hostname = "sandbox.internal.lan"
         node.vm.network :private_network, ip: "192.169.100.7#{i}"
         node.vm.synced_folder "src/", "/opt/src", create: true

         node.vm.provider :virtualbox do |v|
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--memory", 1024]
            v.customize ["modifyvm", :id, "--name", "node#{i}"]
          end
       end
     end
end
