---
- hosts: localhost 
  connection: local
  become: yes
  roles:
        - fubarhouse.golang
        - geerlingguy.docker
        - weareinteractive.users_oh_my_zsh

  vars:
    docker_users:
        - vagrant
    users:
      - name: vagrant
        username: vagrant
        oh_my_zsh:
          theme: gnzh
  tasks:
    - name: Installing git
      package:
         name: git
         state: present
    - name: Compiling gb 
      command: /usr/local/go/bin/go get github.com/constabulary/gb/...
    - name: Copying gb binaries to /usr/local/bin
      copy: remote_src=yes src=/root/go/bin/gb dest=/usr/local/bin mode=o+rx
    - copy: remote_src=yes src=/root/go/bin/gb-vendor dest=/usr/local/bin mode=o+rx
    - name: Cleaning up binaries after copy
      file: path=/root/go state=absent
    - name: Add another go bin dir to system-wide $PATH.
      copy:
        dest: /etc/profile.d/go-path.sh
        content: 'PATH=$PATH:/usr/local/go/bin'
    - name: Clone the pretty zsh powerlevel 10
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: /home/vagrant/.oh-my-zsh/custom/themes/powerlevel10k
    - name: Install Openconnect VPN client
      apt:
        name: openconnect
        state: present
    - name: Install pass for password management
      apt:
        name: pass
        state: present
        
        

 ## Not sure if I want to automatically setup powerlevel theme, there
 ## are a lot of questions, but I'll just comment here on adding it
 ## from the defauly gnzh theme
 #
 ## Then edit your ~/.zshrc and set ZSH_THEME="powerlevel10k/powerlevel10k".
 ## Also add the following: POWERLEVEL9K_MODE="awesome-patched"     
