Vagrant.configure("2") do |config|
  config.vm.define "dockerbox" do |dockerbox|
    dockerbox.vm.box = "geerlingguy/centos7"
    dockerbox.vm.hostname = "dockerbox.internal.lan"
    dockerbox.vm.network :private_network, ip: "192.169.100.73"
    dockerbox.vm.synced_folder "src/", "/opt/src", create: true

    dockerbox.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "dockerbox"]
    end
    dockerbox.vm.provision "docker"
  end

end
